version: '3.4'
services:
  alfresco-promena-predefined-rendition-share:
    image: ${docker.share.image}:${alfresco.share.version}
    environment:
      REPO_HOST: alfresco-promena-predefined-rendition-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"

  alfresco-promena-predefined-rendition-acs:
    image: alfresco-content-services-alfresco-promena-predefined-rendition:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-promena-predefined-rendition-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - alfresco-promena-predefined-rendition-postgres

  alfresco-promena-predefined-rendition-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-promena-predefined-rendition-db-volume:/var/lib/postgresql/data

  alfresco-promena-predefined-rendition-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: alfresco-promena-predefined-rendition-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-promena-predefined-rendition-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - alfresco-promena-predefined-rendition-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-promena-predefined-rendition-ass-volume:/opt/alfresco-search-services/data

  activemq:
    image: alfresco/alfresco-activemq:5.15.6
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
    volumes:
      - alfresco-promena-predefined-rendition-activemq-volume:/opt/activemq/data

  promena:
    image: promena-predefined-rendition-executable:1.0.0
    environment:
      - spring.activemq.broker-url=failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true
      - spring.jms.listener.concurrency=4
      - spring.jms.listener.max-concurrency=4
      - transformer.pl.beone.promena.transformer.mirror.archetype.ArchetypeMirrorTransformer.actors=4

volumes:
  alfresco-promena-predefined-rendition-acs-volume:
    external: true
  alfresco-promena-predefined-rendition-db-volume:
    external: true
  alfresco-promena-predefined-rendition-ass-volume:
    external: true
  alfresco-promena-predefined-rendition-activemq-volume:
    external: true